import {
    registerAppResource,
    registerAppTool,
    RESOURCE_MIME_TYPE,
} from "@modelcontextprotocol/ext-apps/server";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult, ReadResourceResult } from "@modelcontextprotocol/sdk/types.js";
import fs from "node:fs/promises";
import path from "node:path";
import { z } from "zod";
import { pickRandomWord, type WordEntry } from "./words.js";
import { EXCALIDRAW_SYSTEM_PROMPT } from "./excalidraw-prompt.js";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { Mistral } from "@mistralai/mistralai";

const DIST_DIR = import.meta.filename.endsWith(".ts")
    ? path.join(import.meta.dirname, "..", "dist")
    : import.meta.dirname;

// ─── Game State ─────────────────────────────────────────────────────────

interface GameState {
    currentWord: WordEntry;
    attemptsLeft: number;
    revealedLetters: Set<number>;
    won: boolean;
    gameOver: boolean;
}

function createGameState(): GameState {
    return {
        currentWord: pickRandomWord(),
        attemptsLeft: 6,
        revealedLetters: new Set(),
        won: false,
        gameOver: false,
    };
}

function getBlanks(state: GameState): string {
    return state.currentWord.word
        .split("")
        .map((ch, i) => (state.revealedLetters.has(i) ? ch : "_"))
        .join(" ");
}

let gameState = createGameState();

export function getGameState() { return gameState; }
export function resetGameState(): GameState {
    gameState = createGameState();
    return gameState;
}
export function setGameStateFromWord(word: WordEntry): GameState {
    gameState = {
        currentWord: word,
        attemptsLeft: 6,
        revealedLetters: new Set(),
        won: false,
        gameOver: false,
    };
    return gameState;
}
export { getBlanks, pickRandomWord };

// ─── Drawing Generation ──────────────────────────────────────────────────
// Elements are generated by the host LLM via tool input (enabling streaming)

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
    console.warn("GEMINI_API_KEY is not set. Assuming test environment.");
}

const mistralApiKey = process.env.MISTRAL_API_KEY;
if (!mistralApiKey) {
    console.warn("MISTRAL_API_KEY is not set. Assuming test environment.");
}

const genAI = new GoogleGenerativeAI(apiKey || "dummy");
const mistral = new Mistral({ apiKey: mistralApiKey || "dummy" });

/**
 * Streaming drawing generator — yields text chunks as Gemini or Mistral produces them.
 * Used by the /api/draw-stream WebSocket endpoint.
 */
export async function* generateDrawingStream(wordObj: WordEntry, modelName: string = "gemini-3-flash-preview"): AsyncGenerator<string> {
    const isMistral = modelName.includes("istral") || modelName.includes("stral");
    const prompt = `Draw the following ${wordObj.category}: ${wordObj.word}\n\nReturn ONLY the JSON array of Excalidraw elements. Nothing else.`;

    if (!isMistral) {
        if (!apiKey) {
            console.log(`[Pictionary DEV] Mocking stream for "${wordObj.word}"`);
            yield "[]";
            return;
        }

        // Default to gemini-3-flash-preview if a generic name is passed
        const targetModel = modelName === "gemini" ? "gemini-3-flash-preview" : modelName;

        console.log(`[Pictionary STREAM] Generating drawing with ${targetModel} for: ${wordObj.word} (${wordObj.category})...`);
        
        const geminiModel = genAI.getGenerativeModel({
            model: targetModel,
            systemInstruction: {
                role: "system",
                parts: [{ text: EXCALIDRAW_SYSTEM_PROMPT }]
            }
        });

        const result = await geminiModel.generateContentStream(prompt);
        for await (const chunk of result.stream) {
            const text = chunk.text();
            if (text) yield text;
        }
    } else {
        if (!mistralApiKey) {
            console.log(`[Pictionary DEV] Mocking Mistral stream for "${wordObj.word}"`);
            yield "[]";
            return;
        }
        console.log(`[Pictionary STREAM] Generating drawing with ${modelName} for: ${wordObj.word} (${wordObj.category})...`);
        const stream = await mistral.chat.stream({
            model: modelName,
            messages: [
                { role: "system", content: EXCALIDRAW_SYSTEM_PROMPT },
                { role: "user", content: prompt }
            ],
            temperature: 0.7,
        });

        for await (const chunk of stream) {
            const text = chunk.data.choices[0].delta.content;
            if (text && typeof text === "string") yield text;
        }
    }
}

// ─── Server ──────────────────────────────────────────────────────────────

const resourceUri = "ui://pictionary/mcp-app.html";

export function createServer(): McpServer {
    const server = new McpServer({
        name: "pictionary-server",
        version: "1.0.0",
    });

    // ── Tool: draw_pictionary ───────────────────────────────────────────
    registerAppTool(
        server,
        "draw_pictionary",
        {
            title: "Draw Pictionary",
            description: `Start a new Pictionary game. The server will automatically pick a word and generate a drawing using Gemini. No arguments needed.`,
            inputSchema: {},
            _meta: { ui: { resourceUri } },
        },
        async (): Promise<CallToolResult> => {
            const currentWord = pickRandomWord();
            gameState = {
                currentWord,
                attemptsLeft: 6,
                revealedLetters: new Set(),
                won: false,
                gameOver: false,
            };

            return {
                content: [
                    {
                        type: "text",
                        text: JSON.stringify({
                            status: "ready",
                        }),
                    },
                ],
            };
        }
    );

    // ── Tool: check_guess (UI-only) ────────────────────────────────────
    registerAppTool(
        server,
        "check_guess",
        {
            title: "Check Guess",
            description: "Check the player's guess against the current word.",
            inputSchema: {
                guess: z.string().describe("The player's guess"),
            },
            _meta: { ui: { resourceUri, visibility: ["app"] } },
        },
        async (args): Promise<CallToolResult> => {
            const guess = (args.guess as string).toLowerCase().trim();
            // A guess is correct if the exact word matches, OR if the STT phrase contains the secret word
            const targetWord = gameState.currentWord.word.toLowerCase();
            const correct = guess === targetWord || guess.includes(targetWord);

            if (correct) {
                gameState.won = true;
                for (let i = 0; i < gameState.currentWord.word.length; i++) {
                    gameState.revealedLetters.add(i);
                }
            } else {
                gameState.attemptsLeft--;
                // Reveal one random hidden letter as a hint
                const hidden = [];
                for (let i = 0; i < gameState.currentWord.word.length; i++) {
                    if (!gameState.revealedLetters.has(i)) hidden.push(i);
                }
                if (hidden.length > 0) {
                    gameState.revealedLetters.add(hidden[Math.floor(Math.random() * hidden.length)]);
                }
            }

            if (gameState.attemptsLeft <= 0) {
                gameState.gameOver = true;
                for (let i = 0; i < gameState.currentWord.word.length; i++) {
                    gameState.revealedLetters.add(i);
                }
            }

            return {
                content: [
                    {
                        type: "text",
                        text: JSON.stringify({
                            correct,
                            blanks: getBlanks(gameState),
                            attemptsLeft: gameState.attemptsLeft,
                            won: gameState.won,
                            gameOver: gameState.gameOver,
                            word: gameState.won || gameState.gameOver ? gameState.currentWord.word : undefined,
                        }),
                    },
                ],
            };
        }
    );

    // ── Tool: decrement_attempt (UI-only for timeout) ───────────────────
    registerAppTool(
        server,
        "decrement_attempt",
        {
            title: "Decrement Attempt",
            description: "Automatically reduce attempt when timeout occurs.",
            inputSchema: {},
            _meta: { ui: { resourceUri, visibility: ["app"] } },
        },
        async (): Promise<CallToolResult> => {
            if (!gameState.won && !gameState.gameOver && gameState.attemptsLeft > 0) {
                gameState.attemptsLeft--;
                const hidden = [];
                for (let i = 0; i < gameState.currentWord.word.length; i++) {
                    if (!gameState.revealedLetters.has(i)) hidden.push(i);
                }
                if (hidden.length > 0) {
                    gameState.revealedLetters.add(hidden[Math.floor(Math.random() * hidden.length)]);
                }

                if (gameState.attemptsLeft <= 0) {
                    gameState.gameOver = true;
                    for (let i = 0; i < gameState.currentWord.word.length; i++) {
                        gameState.revealedLetters.add(i);
                    }
                }
            }

            return {
                content: [
                    {
                        type: "text",
                        text: JSON.stringify({
                            correct: false,
                            blanks: getBlanks(gameState),
                            attemptsLeft: gameState.attemptsLeft,
                            won: gameState.won,
                            gameOver: gameState.gameOver,
                            word: gameState.won || gameState.gameOver ? gameState.currentWord.word : undefined,
                        }),
                    },
                ],
            };
        }
    );

    // ── Tool: get_game_state (UI-only) ─────────────────────────────────
    registerAppTool(
        server,
        "get_game_state",
        {
            title: "Get Game State",
            description: "Get the current game state.",
            inputSchema: {},
            _meta: { ui: { resourceUri, visibility: ["app"] } },
        },
        async (): Promise<CallToolResult> => {
            return {
                content: [
                    {
                        type: "text",
                        text: JSON.stringify({
                            wordLength: gameState.currentWord.word.length,
                            category: gameState.currentWord.category,
                            blanks: getBlanks(gameState),
                            attemptsLeft: gameState.attemptsLeft,
                            won: gameState.won,
                            gameOver: gameState.gameOver,
                        }),
                    },
                ],
            };
        }
    );

    // ── Resource: bundled React UI ─────────────────────────────────────
    registerAppResource(
        server,
        resourceUri,
        resourceUri,
        {
            mimeType: RESOURCE_MIME_TYPE,
            description: "Pictionary Game UI",
            _meta: {
                ui: {
                    csp: {
                        connectDomains: ["ws://localhost:3001"],
                        resourceDomains: ["https://esm.sh", "wss://api.elevenlabs.io", "https://api.elevenlabs.io", "https://fonts.googleapis.com", "https://fonts.gstatic.com"],
                    },
                    permissions: {
                        microphone: {}
                    }
                }
            }
        },
        async (): Promise<ReadResourceResult> => {
            const html = await fs.readFile(path.join(DIST_DIR, "mcp-app.html"), "utf-8");
            return {
                contents: [{ uri: resourceUri, mimeType: RESOURCE_MIME_TYPE, text: html }],
            };
        }
    );

    return server;
}
